import {
	headlineImage,
	devCheckBox,
	prodCheckBox,
	originalBox,
	instantDevCheck,
	instantPubCheck,
	headline,
	kicker,
	originDiff,
	articleHeadline,
	headlineSummary,
	bulletHeadline,
	bullets,
	urlDescription,
	authorName,
	brief,
	headlineImageAlt,
	headlineImageAttribution,
	headlineImageAttributionLink,
	longUrl,
	longMobileUrl,
	shareCount,
	shortUrl,
	shortMobileUrl,
	tags,
} from "./layoutFields";

const INITIAL_ARTICLE_OVERVIEW = {
	id: "",
	authorId: "",
	authorName: "",
	brief: "",
	category: "",
	headline: "",
	original: false,
	articleHeadline: "",
	bulletHeadlines: "",
	bulletHeadlinesDetails: {},
	headlineSummary: "",
	headlineImage: "",
	headlineImageAlt: "",
	headlineImageAttribution: "",
	headlineImageAttributionLink: "",
	instantDevelopmentCheck: false,
	instantPublishCheck: false,
	kicker: "",
	originDiff: "",
	longUrl: "",
	longMobileUrl: "",
	shareCount: "",
	shortUrl: "",
	shortMobileUrl: "",
	articleSiteId: "",
	site: "",
	tags: [],
	tag: "",
	urlDescription: "",
	development: false,
	production: false,
	productionId: "",
	pushDate: "",
	schedule: "",
	scheduleTime: "",
	mainHeadline: false,
	sideHeadline: false,
	displayDate: "",
};

const initialLayout = [
	headlineImage,
	headline,
	kicker,
	articleHeadline,
	headlineSummary,
	bulletHeadline,
	bullets,
	urlDescription,
	brief,
	headlineImageAlt,
	headlineImageAttribution,
	headlineImageAttributionLink,
	tags,
];
const developmentLayout = [
	headlineImage,
	devCheckBox,
	prodCheckBox,
	originalBox,
	{
		id: "Headline",
		label: "Headline",
		type: "text",
		name: "headline",
		width: "90%",
		layout: "block",
		gridCol: 1,
	},
	kicker,
	articleHeadline,
	headlineSummary,
	bulletHeadline,
	bullets,
	urlDescription,
	authorName,
	brief,
	headlineImageAlt,
	headlineImageAttribution,
	headlineImageAttributionLink,
	tags,
];
const productionLayout = [
	headlineImage,
	devCheckBox,
	prodCheckBox,
	originalBox,
	instantDevCheck,
	instantPubCheck,
	headline,
	kicker,
	articleHeadline,
	headlineSummary,
	bulletHeadline,
	bullets,
	urlDescription,
	authorName,
	brief,
	headlineImageAlt,
	headlineImageAttribution,
	headlineImageAttributionLink,
	longUrl,
	longMobileUrl,
	shareCount,
	shortUrl,
	shortMobileUrl,
	tags,
];
const layout = {
	initial: initialLayout,
	development: developmentLayout,
	production: productionLayout,
	duplicateDevelopment: [originDiff, ...developmentLayout],
	duplicateProduction: [originDiff, ...productionLayout],
};

const requiredValues = [
	"headline",
	"articleHeadline",
	"headlineSummary",
	"kicker",
	"urlDescription",
	"brief",
	"headlineImageAlt",
];
export { INITIAL_ARTICLE_OVERVIEW, layout, requiredValues };
