projects:
  dashboardApi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: 3riu2k6vwbbnbgqxn2lcs5ht7y
      endpoints:
        prod: >-
          https://ozde7boayvbdvcyzqjti65jkym.appsync-api.eu-west-1.amazonaws.com/graphql
