import {
	headlineImage,
	devCheckBox,
	prodCheckBox,
	originalBox,
	title,
	originDiff,
	headlineImageAlt,
	headlineImageAttribution,
	headlineImageAttributionLink,
	blurb,
	comments,
	scoreComments,
	quizUrl,
	metaTag,
	quizTitle,
	authorName,
	longUrl,
	longMobileUrl,
	shareCount,
	shortUrl,
	shortMobileUrl,
	quizTag,
} from "./quizLayoutFields";

const initialLayout = [
	headlineImage,
	title,
	blurb,
	comments,
	scoreComments,
	quizUrl,
	quizTitle,
	metaTag,
	headlineImageAlt,
	headlineImageAttribution,
	headlineImageAttributionLink,
	quizTag,
];

const developmentLayout = [
	headlineImage,
	devCheckBox,
	prodCheckBox,
	originalBox,
	title,
	authorName,
	blurb,
	comments,
	scoreComments,
	quizUrl,
	metaTag,
	quizTitle,
	headlineImageAlt,
	headlineImageAttribution,
	headlineImageAttributionLink,
	quizTag,
];

const productionLayout = [
	headlineImage,
	devCheckBox,
	prodCheckBox,
	originalBox,
	title,
	blurb,
	comments,
	scoreComments,
	quizUrl,
	metaTag,
	authorName,
	quizTitle,
	headlineImageAlt,
	headlineImageAttribution,
	headlineImageAttributionLink,
	longUrl,
	longMobileUrl,
	shareCount,
	shortUrl,
	shortMobileUrl,
	quizTag,
];
const layout = {
	initial: initialLayout,
	development: developmentLayout,
	production: productionLayout,
	duplicateDevelopment: [originDiff, ...developmentLayout],
	duplicateProduction: [originDiff, ...productionLayout],
};
export { layout };
