import {
	headlineImage,
	devCheckBox,
	prodCheckBox,
	originalBox,
	title,
	originDiff,
	headlineImageAlt,
	headlineImageAttribution,
	headlineImageAttributionLink,
	blurb,
	slideUrl,
	slideTitle,
	slideTag,
	metaTag,
	authorName,
	longUrl,
	longMobileUrl,
	shareCount,
	shortUrl,
	shortMobileUrl,
	showNumbers,
	countDown,
} from "./slideLayoutFields";

const initialLayout = [
	headlineImage,
	title,
	blurb,
	slideUrl,
	metaTag,
	slideTitle,
	headlineImageAlt,
	headlineImageAttribution,
	headlineImageAttributionLink,
	slideTag,
];

const developmentLayout = [
	headlineImage,
	devCheckBox,
	prodCheckBox,
	showNumbers,
	countDown,
	originalBox,
	title,
	authorName,
	blurb,
	slideUrl,
	metaTag,
	slideTitle,
	headlineImageAlt,
	headlineImageAttribution,
	headlineImageAttributionLink,
	slideTag,
];

const productionLayout = [
	headlineImage,
	devCheckBox,
	prodCheckBox,
	showNumbers,
	countDown,
	originalBox,
	title,
	blurb,
	slideUrl,
	metaTag,
	authorName,
	slideTitle,
	headlineImageAlt,
	headlineImageAttribution,
	headlineImageAttributionLink,
	longUrl,
	longMobileUrl,
	shareCount,
	shortUrl,
	shortMobileUrl,
	slideTag,
];
const layout = {
	initial: initialLayout,
	development: developmentLayout,
	production: productionLayout,
	duplicateDevelopment: [originDiff, ...developmentLayout],
	duplicateProduction: [originDiff, ...productionLayout],
};

export { layout };
